version: 2
updates:
- package-ecosystem: mix
  directory: "/distributor"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.0
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
  - dependency-name: libcluster
    versions:
    - 3.2.1
- package-ecosystem: npm
  directory: "/distributor-js"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 3.9.9
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
