name: Build Docker Image

on: [push]

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fknop/distributor:$GITHUB_SHA
