name: Build Docker Image

on:
  pull_request:
    paths:
      - 'distributor/**'

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      working-directory: ./distributor
      run: docker build . --file Dockerfile --tag fknop/distributor:$GITHUB_SHA
