name: Elixir CI

on:
  pull_request:
    paths:
      - 'distributor/**'
jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      working-directory: ./distributor
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      working-directory: ./distributor
      run: mix test
