name: Build Docker Image

on:
  push:
    branches:
      - master
      - develop
jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      working-directory: ./distributor
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/fknop/distributor/distributor-api:$GITHUB_SHA
    - name: Publish the docker image
      working-directory: ./distributor
      run: |
        docker login docker.pkg.github.com -u fknop -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/fknop/distributor/distributor-api:$GITHUB_SHA
