name: Elixir CI

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4-slim



    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ./distributor/deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/distributor/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - name: Install Dependencies
      working-directory: ./distributor
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get


    - name: Run Tests
      working-directory: ./distributor
      run: mix test
